baseURL = "https://tobi-demming.github.io/homepage/"
languageCode = "en-us"
title = "Tobias"
theme = "PaperMod"
[pagination]
  pagerSize = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  author = "Tobias"
  description = "Product Owner · Data Science · Media Automation"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = true
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    Title = "hi, I'm Tobias."
    Content = "Product Owner · Data Scientist · Media Automation enthusiast. Based in Germany."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/tobi-demming/"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/tobias-demming"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:hello@tobias"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "mediablog"
    name = "mediablog"
    url = "/mediablog/"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "catppuccin-macchiato"
